services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command: [redpanda, start, --mode=dev-container, --smp=1,
              --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092,
              --advertise-kafka-addr=internal://redpanda:9092,external://localhost:19092]
    ports: ["19092:19092"]
  dynamodb:
    image: amazon/dynamodb-local:latest
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    ports: ["8000:8000"]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
