if(RIDGELINE_SANITIZE STREQUAL "address")
  add_compile_options(-fsanitize=address,undefined -fno-omit-frame-pointer -fno-sanitize-recover=all)
  add_link_options(-fsanitize=address,undefined)
elseif(RIDGELINE_SANITIZE STREQUAL "thread")
  add_compile_options(-fsanitize=thread -fno-omit-frame-pointer)
  add_link_options(-fsanitize=thread)
elseif(NOT RIDGELINE_SANITIZE STREQUAL "")
  message(FATAL_ERROR "Unknown RIDGELINE_SANITIZE value: ${RIDGELINE_SANITIZE}")
endif()
